import { NextResponse } from 'next/server';
import { buildMinimalPdf } from '@/lib/minimalPdf';
import { requireSession } from '@/lib/sessionAuth';

export async function GET(req: Request) {
  const user = await requireSession();
  if (user instanceof NextResponse) return user;

  const url = new URL(req.url);
  const title = url.searchParams.get('title') || 'InnerOS ISKCON artifact';
  const body = url.searchParams.get('body') || '';
  const filename = url.searchParams.get('filename') || 'artifact.pdf';
  const lines = body.split('\n').filter(Boolean);
  if (lines.length === 0) {
    lines.push('Generated by InnerOS ISKCON Desk (local artifact engine).');
    lines.push(`Tenant: ${user.companyId || 'iskcon'}`);
    lines.push(`Date: ${new Date().toISOString()}`);
  }

  const pdf = buildMinimalPdf(title, lines);
  return new NextResponse(new Uint8Array(pdf), {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename.replace(/[^a-zA-Z0-9._-]/g, '_')}"`,
      'Cache-Control': 'no-store',
    },
  });
}
