import { moduleOAuthRedirectUris } from '@/lib/moduleDomains';

export type InnerOSLang = 'en' | 'es';

export const INNEROS_BRAND = {
  name: 'InnerOS',
  logoPath: '/brands/inneros.svg',
  accentFrom: 'from-blue-500',
  accentTo: 'to-purple-600',
} as const;

const moduleDescriptionsEn = {
  'workforce-ai':
    'Assistance, schedules, ZKTeco/Hikvision, prepayroll, reports, and Gemini ARIA.',
  'iskcon-desk':
    'Panihati sponsors, letters, dossiers, and WhatsApp capture (Guayaquil pilot).',
  visitors: 'Gatehouse, visitors, QR, lobby/gate roles, Hikvision ISAPI bridge.',
  'fieldspark-photography':
    'Photography studio vertical — smart-quoter + quoteops (Joshua Degel, RAW/JPG, 6 commercial phases).',
  'smart-quoter':
    'Audio-powered quotes — photography studio vertical (Joshua Degel) and commercial.',
  quoteops: 'Full commercial flow: missions, WhatsApp, MCP, FEMAR, and photography.',
  founderos: 'Founder dashboard, metrics, daily memory, and strategic decisions.',
  credentials: 'Identity and credentials per company (server-side).',
  'inneros-admin': 'Internal ops panel — fleet, MCP, services (:2002).',
  'a2a-gateway': 'A2A v1 fabric — multi-agent routing (technical team only).',
} as const;

const moduleDescriptionsEs = {
  'workforce-ai':
    'Asistencia, horarios, ZKTeco/Hikvision, prepayroll, reportes y ARIA Gemini.',
  'iskcon-desk':
    'Patrocinadores Panihati, cartas, dossiers y captura WhatsApp (piloto Guayaquil).',
  visitors: 'Garita, visitantes, QR, roles lobby/garita, bridge Hikvision ISAPI.',
  'fieldspark-photography':
    'Vertical estudio fotográfico — smart-quoter + quoteops (Joshua Degel, RAW/JPG, 6 fases comerciales).',
  'smart-quoter':
    'Cotizaciones con audio — vertical estudio fotográfico (Joshua Degel) y comercial.',
  quoteops: 'Flujo comercial completo: misiones, WhatsApp, MCP, FEMAR y foto.',
  founderos: 'Panel fundador, métricas, memoria diaria y decisiones estratégicas.',
  credentials: 'Identidad y credenciales por empresa (server-side).',
  'inneros-admin': 'Panel ops interno — fleet, MCP, servicios (:2002).',
  'a2a-gateway': 'Fabric A2A v1 — enrutamiento multi-agente (solo equipo técnico).',
} as const;

export const innerosCopy = {
  en: {
    common: {
      loading: 'Loading…',
      connectionError: 'Connection error',
      genericError: 'Something went wrong',
      switchLanguage: 'Switch language',
      langToggle: 'Español',
      send: 'Send',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      corporateEmailPlaceholder: 'name@company.com',
    },
    shell: {
      language: 'Language',
      signOut: 'Sign out',
      closeMenu: 'Close menu',
    },
    login: {
      headline: 'The operating layer',
      headlineAccent: 'for your business.',
      subline:
        'Sign in once. Step into workforce, visitors, quotes, and every module your company runs — privately, by tenant.',
      signIn: 'Sign in',
      username: 'Username or ID',
      password: 'Password',
      google: 'Continue with Google',
      googleError: 'Google sign-in failed. Ask your admin to authorize this domain in Google Console.',
      googleFailed: 'Google sign-in failed due to a technical error. Please try again in a moment.',
      googleState: 'Your Google sign-in session expired or was interrupted. Click "Continue with Google" again.',
      googlePending: 'Your access request is pending administrator approval.',
      googleRedirectHint: 'Redirect URI mismatch — register this site callback in Google Cloud OAuth.',
      accountRejected: 'Your access request was rejected. Contact your administrator.',
      onboardingExpired: 'Your Google registration session expired. Please try "Continue with Google" again.',
      invalid: 'Invalid credentials',
      required: 'Enter username and password',
      registerPrompt: 'Need access?',
      registerLink: 'Request an account (without Google)',
      loginHint: 'Sign in with your ID or email + password, or use Google.',
      footer: 'InnerOS',
    },
    register: {
      title: 'Request access',
      subtitle: 'Register without Google. An administrator must approve before you can sign in.',
      submit: 'Submit request',
      loading: 'Submitting…',
      note: 'After approval, sign in with your ID + password or Google if linked.',
      hasAccount: 'Already have an account?',
      login: 'Sign in',
    },
    onboarding: {
      title: 'Complete your registration',
      subtitle:
        'Google verified your email. Complete your legal and contact details. An administrator will review your request.',
      submit: 'Submit request to administrator',
      loading: 'Submitting…',
      note: 'You cannot sign in until approved. You will receive email confirmation.',
    },
    pendingApproval: {
      submittedTitle: 'Thank you! Request submitted',
      submittedBody: 'Your request was received and is under review by the InnerOS administrator.',
      submittedEmail:
        'We will email you shortly when your access is active. You can sign in with Google or your local ID and password.',
      submittedWait: 'You do not need to do anything else for now. You can close this window.',
      reviewTitle: 'Request under review',
      reviewBody: 'Your registration is still pending administrator approval.',
      reviewEmail:
        'Once approved, you can sign in with Google or ID + password depending on how you registered.',
      reviewWait: 'If you just submitted the form, check your email in the next few hours.',
      backToLogin: 'Back to sign in',
    },
    registrationForm: {
      documentCountry: 'Document country *',
      idType: 'ID type *',
      firstName1: 'First name *',
      firstName2: 'Middle name',
      lastName1: 'First surname *',
      lastName2: 'Second surname *',
      birthDate: 'Date of birth *',
      googleEmail: 'Email verified by Google',
      googleEmailHint: 'This email was verified by Google and cannot be changed.',
      corporateEmail: 'Corporate email',
      corporateEmailHint: 'Optional. If your company uses a different email than Google.',
      email: 'Email *',
      phone: 'Phone / WhatsApp *',
      address: 'Address *',
      city: 'City *',
      residenceCountry: 'Country of residence *',
      password: 'Local password (backup if Google fails) *',
      passwordConfirm: 'Confirm password *',
      joinExisting: 'Join an existing company',
      joinHint: 'Type the company name. Admin confirms the tenant.',
      newTenant: 'Register my new company (SaaS customer)',
      companyName: 'Company name *',
    },
    validation: {
      fieldRequired: (label: string) => `${label} is required`,
      fieldMinLength: (label: string, min: number) => `${label} must be at least ${min} characters`,
      fieldLettersOnly: (label: string) => `${label} may only contain letters`,
      emailRequired: 'Email is required',
      emailInvalid: 'Invalid email address',
      phoneRequired: 'Phone / WhatsApp is required',
      phoneMinDigits: 'Phone / WhatsApp must have at least 8 digits',
      phoneTooLong: 'Phone / WhatsApp is too long',
      birthDateRequired: 'Date of birth is required',
      birthDateInvalid: 'Invalid date of birth',
      birthDateFuture: 'Date of birth cannot be in the future',
      birthDateTooYoung: 'You must be at least 16 years old',
      addressRequired: (label: string) => `${label} is required (minimum 3 characters)`,
      companyNameRequired: 'Enter the company name (minimum 2 characters)',
      passwordRequired: 'Password is required',
      passwordConfirmRequired: 'Confirm your password',
      passwordMismatch: 'Passwords do not match',
      labels: {
        firstName1: 'First name',
        firstName2: 'Middle name',
        lastName1: 'First surname',
        lastName2: 'Second surname',
        address: 'Address',
        city: 'City',
      },
      identity: {
        ecCedula: 'Invalid Ecuadorian ID (10 digits, modulo 10)',
        coCedula: 'Invalid Colombian ID (6-10 digits)',
        peDni: 'Invalid Peruvian DNI (8 digits)',
        mxCurp: 'Invalid CURP (basic 18-character format)',
        esDni: 'Invalid Spanish DNI (8 digits + letter)',
        esNie: 'Invalid NIE (X/Y/Z + 7 digits + letter)',
        passport: 'Invalid passport (6-20 alphanumeric characters)',
        driverLicense: 'Invalid license (5-20 alphanumeric characters)',
        generic: 'Invalid document (5-20 alphanumeric characters)',
      },
    },
    modules: {
      title: 'Choose your module',
      subtitle: 'Each product opens in its own workspace. Your data stays isolated by company.',
      open: 'Open',
      soon: 'Coming soon',
      beta: 'Beta',
      workspace: 'Workspace',
      accessDenied: 'Access denied for this module',
      descriptions: moduleDescriptionsEn,
    },
    aria: {
      label: 'ARIA',
      subtitle: 'Gemini assistant',
      welcome:
        "I'm ARIA. Type help to see all modules with explanations, or ask about workforce, visitors, quotes, or quoteops.",
      placeholder: 'Try: open workforce · register a visitor · start a quote…',
      thinking: 'Thinking…',
      guestReply:
        "Sign in first and I'll take you there. You can also use username/password above, then ask me again from your workspace.",
      basicReply: 'Try workforce, visitors, quoter, or quoteops — or sign in for full assistance.',
      openModule: 'Open module',
      hello: 'Hello! Once you sign in, I can route you to any module your company uses.',
      newChat: 'New chat',
      clearHistory: 'Clear history',
      voiceOn: 'Voice on',
      voiceOff: 'Voice off',
      history: 'History',
      noHistory: 'No saved chats',
      speak: 'Listen',
      listen: 'Voice input',
      listening: 'Listening…',
      micUnsupported: 'Voice input not supported in this browser',
      tools: 'Options',
      toolsMenu: 'Options',
      ttsFailed: 'Voice playback unavailable',
      ttsKokoro: 'Voice: Kokoro (local)',
      ttsBrowser: 'Voice: browser',
      clearHistoryDone: 'History cleared',
    },
  },
  es: {
    common: {
      loading: 'Cargando…',
      connectionError: 'Error de conexión',
      genericError: 'Ocurrió un error',
      switchLanguage: 'Cambiar idioma',
      langToggle: 'English',
      send: 'Enviar',
      showPassword: 'Mostrar contraseña',
      hidePassword: 'Ocultar contraseña',
      corporateEmailPlaceholder: 'nombre@empresa.com',
    },
    shell: {
      language: 'Idioma',
      signOut: 'Cerrar sesión',
      closeMenu: 'Cerrar menú',
    },
    login: {
      headline: 'La capa operativa',
      headlineAccent: 'de tu empresa.',
      subline:
        'Un solo acceso. Entra a workforce, visitantes, cotizaciones y cada módulo que tu empresa usa — aislado por tenant.',
      signIn: 'Ingresar',
      username: 'Usuario o cédula',
      password: 'Contraseña',
      google: 'Continuar con Google',
      googleError: 'Falló el inicio con Google. Autoriza este dominio en Google Console.',
      googleFailed: 'Falló el inicio con Google por un error técnico. Intenta de nuevo en unos momentos.',
      googleState: 'Tu sesión de Google expiró o se interrumpió. Pulsa "Continuar con Google" otra vez.',
      googlePending: 'Tu solicitud de acceso está pendiente de aprobación del administrador.',
      googleRedirectHint: 'Redirect URI mismatch — registra el callback de este sitio en OAuth de Google.',
      accountRejected: 'Tu solicitud de acceso fue rechazada. Contacta al administrador.',
      onboardingExpired: 'Tu sesión de registro con Google expiró. Vuelve a pulsar "Continuar con Google".',
      invalid: 'Credenciales inválidas',
      required: 'Ingresa usuario y contraseña',
      registerPrompt: '¿Necesitas acceso?',
      registerLink: 'Solicitar cuenta (sin Google)',
      loginHint: 'Entra con cédula o correo + contraseña, o usa Google.',
      footer: 'InnerOS',
    },
    register: {
      title: 'Solicitar acceso',
      subtitle: 'Registro sin Google. Un administrador debe aprobar tu cuenta antes de entrar.',
      submit: 'Enviar solicitud',
      loading: 'Enviando…',
      note: 'Tras aprobar, podrás entrar con tu documento + contraseña o Google si lo vinculas.',
      hasAccount: '¿Ya tienes cuenta?',
      login: 'Iniciar sesión',
    },
    onboarding: {
      title: 'Completa tu registro',
      subtitle:
        'Google autorizó tu correo. Completa tus datos legales y de contacto. Un administrador revisará tu solicitud.',
      submit: 'Enviar solicitud al administrador',
      loading: 'Enviando…',
      note: 'No podrás entrar hasta que el administrador apruebe. Recibirás confirmación por correo.',
    },
    pendingApproval: {
      submittedTitle: '¡Gracias! Solicitud enviada',
      submittedBody: 'Tu solicitud fue recibida y está en revisión por el administrador de InnerOS.',
      submittedEmail:
        'Te enviaremos un correo en breve cuando tu acceso esté activo. Podrás entrar con Google o con tu documento y contraseña local.',
      submittedWait: 'Por ahora no necesitas hacer nada más. Puedes cerrar esta ventana.',
      reviewTitle: 'Solicitud en revisión',
      reviewBody: 'Tu registro sigue pendiente de aprobación por el administrador.',
      reviewEmail:
        'Cuando se apruebe, podrás entrar con Google o con documento + contraseña según hayas registrado.',
      reviewWait: 'Si acabas de enviar el formulario, revisa tu correo en las próximas horas.',
      backToLogin: 'Volver al inicio de sesión',
    },
    registrationForm: {
      documentCountry: 'País del documento *',
      idType: 'Tipo de identificación *',
      firstName1: 'Primer nombre *',
      firstName2: 'Segundo nombre',
      lastName1: 'Primer apellido *',
      lastName2: 'Segundo apellido *',
      birthDate: 'Fecha de nacimiento *',
      googleEmail: 'Correo verificado por Google',
      googleEmailHint: 'Este correo fue verificado por Google y no se puede modificar.',
      corporateEmail: 'Correo electrónico corporativo',
      corporateEmailHint: 'Opcional. Si tu empresa usa otro correo distinto al de Google.',
      email: 'Correo electrónico *',
      phone: 'Teléfono / WhatsApp *',
      address: 'Dirección *',
      city: 'Ciudad *',
      residenceCountry: 'País de residencia *',
      password: 'Contraseña local (respaldo si Google falla) *',
      passwordConfirm: 'Confirmar contraseña *',
      joinExisting: 'Unirme a una empresa existente',
      joinHint: 'Escribe el nombre de la empresa. El administrador confirma el tenant.',
      newTenant: 'Registrar mi empresa nueva (cliente SaaS)',
      companyName: 'Nombre de la empresa *',
    },
    validation: {
      fieldRequired: (label: string) => `${label} es obligatorio`,
      fieldMinLength: (label: string, min: number) => `${label} debe tener al menos ${min} caracteres`,
      fieldLettersOnly: (label: string) => `${label} solo puede contener letras`,
      emailRequired: 'Correo electrónico obligatorio',
      emailInvalid: 'Correo electrónico inválido',
      phoneRequired: 'Teléfono / WhatsApp obligatorio',
      phoneMinDigits: 'Teléfono / WhatsApp debe tener al menos 8 dígitos',
      phoneTooLong: 'Teléfono / WhatsApp demasiado largo',
      birthDateRequired: 'Fecha de nacimiento obligatoria',
      birthDateInvalid: 'Fecha de nacimiento inválida',
      birthDateFuture: 'La fecha de nacimiento no puede ser futura',
      birthDateTooYoung: 'Debes tener al menos 16 años',
      addressRequired: (label: string) => `${label} es obligatorio (mínimo 3 caracteres)`,
      companyNameRequired: 'Indica el nombre de la empresa (mínimo 2 caracteres)',
      passwordRequired: 'Contraseña obligatoria',
      passwordConfirmRequired: 'Confirma tu contraseña',
      passwordMismatch: 'Las contraseñas no coinciden',
      labels: {
        firstName1: 'Primer nombre',
        firstName2: 'Segundo nombre',
        lastName1: 'Primer apellido',
        lastName2: 'Segundo apellido',
        address: 'Dirección',
        city: 'Ciudad',
      },
      identity: {
        ecCedula: 'Cédula ecuatoriana inválida (10 dígitos, módulo 10)',
        coCedula: 'Cédula colombiana inválida (6-10 dígitos)',
        peDni: 'DNI peruano inválido (8 dígitos)',
        mxCurp: 'CURP inválida (formato básico 18 caracteres)',
        esDni: 'DNI español inválido (8 dígitos + letra)',
        esNie: 'NIE inválido (X/Y/Z + 7 dígitos + letra)',
        passport: 'Pasaporte inválido (6-20 caracteres alfanuméricos)',
        driverLicense: 'Licencia inválida (5-20 caracteres alfanuméricos)',
        generic: 'Documento inválido (5-20 caracteres alfanuméricos)',
      },
    },
    modules: {
      title: 'Elige tu módulo',
      subtitle: 'Cada producto abre en su propio espacio. Tus datos quedan aislados por empresa.',
      open: 'Abrir',
      soon: 'Próximamente',
      beta: 'Beta',
      workspace: 'Espacio',
      accessDenied: 'Acceso denegado a este módulo',
      descriptions: moduleDescriptionsEs,
    },
    aria: {
      label: 'ARIA',
      subtitle: 'Asistente Gemini',
      welcome:
        'Soy ARIA. Escribe ayuda para ver todos los módulos con explicación, o dime workforce, visitantes, cotizaciones o quoteops.',
      placeholder: 'Ej.: abrir workforce · registrar visitante · cotizar…',
      thinking: 'Pensando…',
      guestReply:
        'Inicia sesión primero y te llevo. También puedes usar usuario/contraseña arriba y preguntarme de nuevo en tu espacio.',
      basicReply: 'Prueba workforce, visitantes, cotizador o quoteops — o inicia sesión para ayuda completa.',
      openModule: 'Abrir módulo',
      hello: '¡Hola! Cuando inicies sesión podré llevarte a cualquier módulo de tu empresa.',
      newChat: 'Nuevo chat',
      clearHistory: 'Borrar historial',
      voiceOn: 'Voz activada',
      voiceOff: 'Voz desactivada',
      history: 'Historial',
      noHistory: 'Sin chats guardados',
      speak: 'Escuchar',
      listen: 'Entrada por voz',
      listening: 'Escuchando…',
      micUnsupported: 'Entrada por voz no disponible en este navegador',
      tools: 'Opciones',
      toolsMenu: 'Opciones',
      ttsFailed: 'Reproducción de voz no disponible',
      ttsKokoro: 'Voz: Kokoro (local)',
      ttsBrowser: 'Voz: navegador',
      clearHistoryDone: 'Historial borrado',
    },
  },
} as const;

export function t(lang: InnerOSLang) {
  return innerosCopy[lang];
}

export function moduleDescription(moduleId: string, lang: InnerOSLang, fallback = ''): string {
  const descriptions = innerosCopy[lang].modules.descriptions;
  return descriptions[moduleId as keyof typeof descriptions] ?? fallback;
}

/** Redirect URIs Rafael must register in Google Cloud Console → OAuth client */
export const GOOGLE_OAUTH_REDIRECT_URIS = moduleOAuthRedirectUris();
