export const mockEmployees = [
  {
    "id": "1717016487",
    "firstName": "Xavier",
    "secondName": "Gabriel",
    "firstLastName": "Cevallos",
    "secondLastName": "Morales",
    "name": "Xavier Gabriel Cevallos Morales",
    "role": "CFO",
    "department": "Directorio Corporativo",
    "phone": "+593 907513633",
    "email": "xavier.cevallos70@outlook.com",
    "address": "Calle 95 y Av. Principal, Quito",
    "dob": "1979-07-19",
    "photo": "https://i.pravatar.cc/150?img=1",
    "status": "Activo",
    "baseSalary": 2275,
    "companyId": "femar"
  },
  {
    "id": "0333269413",
    "firstName": "José",
    "secondName": "David",
    "firstLastName": "Torres",
    "secondLastName": "Vargas",
    "name": "José David Torres Vargas",
    "role": "Director de Ventas",
    "department": "Ventas",
    "phone": "+593 932565851",
    "email": "josé.torres86@yahoo.com",
    "address": "Calle 93 y Av. Principal, Quito",
    "dob": "1992-10-25",
    "photo": "https://i.pravatar.cc/150?img=65",
    "status": "Permiso Médico",
    "baseSalary": 1881,
    "companyId": "femar"
  },
  {
    "id": "1836558898",
    "firstName": "Jorge",
    "secondName": "Andrés",
    "firstLastName": "García",
    "secondLastName": "Castro",
    "name": "Jorge Andrés García Castro",
    "role": "Analista de Mercadeo",
    "department": "Marketing",
    "phone": "+593 984084443",
    "email": "jorge.garcía82@gmail.com",
    "address": "Calle 10 y Av. Principal, Quito",
    "dob": "1975-06-14",
    "photo": "https://i.pravatar.cc/150?img=65",
    "status": "Activo",
    "baseSalary": 2247,
    "companyId": "femar"
  },
  {
    "id": "2453923548",
    "firstName": "Alejandro",
    "secondName": "Fernando",
    "firstLastName": "Castro",
    "secondLastName": "Almeida",
    "name": "Alejandro Fernando Castro Almeida",
    "role": "Reclutador",
    "department": "Recursos Humanos",
    "phone": "+593 959731895",
    "email": "alejandro.castro49@yahoo.com",
    "address": "Calle 35 y Av. Principal, Quito",
    "dob": "1988-03-02",
    "photo": "https://i.pravatar.cc/150?img=69",
    "status": "Activo",
    "baseSalary": 1877,
    "companyId": "femar"
  },
  {
    "id": "0853072775",
    "firstName": "Laura",
    "secondName": "Carolina",
    "firstLastName": "Delgado",
    "secondLastName": "García",
    "name": "Laura Carolina Delgado García",
    "role": "Soporte Técnico",
    "department": "IT",
    "phone": "+593 957703847",
    "email": "laura.delgado45@outlook.com",
    "address": "Calle 45 y Av. Principal, Quito",
    "dob": "1987-12-12",
    "photo": "https://i.pravatar.cc/150?img=44",
    "status": "Activo",
    "baseSalary": 549,
    "companyId": "femar"
  },
  {
    "id": "2201015415",
    "firstName": "Daniel",
    "secondName": "Jorge",
    "firstLastName": "López",
    "secondLastName": "Aguilar",
    "name": "Daniel Jorge López Aguilar",
    "role": "Coordinador de Planta",
    "department": "Operaciones",
    "phone": "+593 918883000",
    "email": "daniel.lópez77@outlook.com",
    "address": "Calle 40 y Av. Principal, Quito",
    "dob": "1997-04-03",
    "photo": "https://i.pravatar.cc/150?img=2",
    "status": "Vacaciones",
    "baseSalary": 798,
    "companyId": "femar"
  },
  {
    "id": "2239263748",
    "firstName": "José",
    "secondName": "Carlos",
    "firstLastName": "Cevallos",
    "secondLastName": "Almeida",
    "name": "José Carlos Cevallos Almeida",
    "role": "CFO",
    "department": "Directorio Corporativo",
    "phone": "+593 994631415",
    "email": "josé.cevallos69@hotmail.com",
    "address": "Calle 21 y Av. Principal, Quito",
    "dob": "1995-04-09",
    "photo": "https://i.pravatar.cc/150?img=20",
    "status": "Activo",
    "baseSalary": 1689,
    "companyId": "femar"
  },
  {
    "id": "1125564482",
    "firstName": "Xavier",
    "secondName": "Andrés",
    "firstLastName": "Navas",
    "secondLastName": "Ortiz",
    "name": "Xavier Andrés Navas Ortiz",
    "role": "Supervisor de Ventas",
    "department": "Ventas",
    "phone": "+593 946211783",
    "email": "xavier.navas79@outlook.com",
    "address": "Calle 99 y Av. Principal, Quito",
    "dob": "1984-12-17",
    "photo": "https://i.pravatar.cc/150?img=49",
    "status": "Activo",
    "baseSalary": 1785,
    "companyId": "femar"
  },
  {
    "id": "2342431760",
    "firstName": "Xavier",
    "secondName": "Pedro",
    "firstLastName": "Mendoza",
    "secondLastName": "Pérez",
    "name": "Xavier Pedro Mendoza Pérez",
    "role": "Analista de Mercadeo",
    "department": "Marketing",
    "phone": "+593 910373138",
    "email": "xavier.mendoza84@outlook.com",
    "address": "Calle 1 y Av. Principal, Quito",
    "dob": "1988-09-03",
    "photo": "https://i.pravatar.cc/150?img=62",
    "status": "Activo",
    "baseSalary": 1553,
    "companyId": "femar"
  },
  {
    "id": "1029043567",
    "firstName": "Luis",
    "secondName": "Daniel",
    "firstLastName": "Molina",
    "secondLastName": "Romero",
    "name": "Luis Daniel Molina Romero",
    "role": "Reclutador",
    "department": "Recursos Humanos",
    "phone": "+593 979806302",
    "email": "luis.molina57@yahoo.com",
    "address": "Calle 48 y Av. Principal, Quito",
    "dob": "1980-01-21",
    "photo": "https://i.pravatar.cc/150?img=55",
    "status": "Vacaciones",
    "baseSalary": 1802,
    "companyId": "femar"
  },
  {
    "id": "0416772028",
    "firstName": "Paola",
    "secondName": "Silvia",
    "firstLastName": "Castro",
    "secondLastName": "Zambrano",
    "name": "Paola Silvia Castro Zambrano",
    "role": "SysAdmin",
    "department": "IT",
    "phone": "+593 962366991",
    "email": "paola.castro65@gmail.com",
    "address": "Calle 14 y Av. Principal, Quito",
    "dob": "1983-10-19",
    "photo": "https://i.pravatar.cc/150?img=39",
    "status": "Permiso Médico",
    "baseSalary": 1924,
    "companyId": "femar"
  },
  {
    "id": "0613357987",
    "firstName": "Eduardo",
    "secondName": "Pedro",
    "firstLastName": "Cevallos",
    "secondLastName": "Luna",
    "name": "Eduardo Pedro Cevallos Luna",
    "role": "Gerente de Operaciones",
    "department": "Operaciones",
    "phone": "+593 986931099",
    "email": "eduardo.cevallos78@yahoo.com",
    "address": "Calle 97 y Av. Principal, Quito",
    "dob": "1989-03-10",
    "photo": "https://i.pravatar.cc/150?img=31",
    "status": "Activo",
    "baseSalary": 569,
    "companyId": "femar"
  },
  {
    "id": "1231754175",
    "firstName": "Rosa",
    "secondName": "Valeria",
    "firstLastName": "Vargas",
    "secondLastName": "Morales",
    "name": "Rosa Valeria Vargas Morales",
    "role": "CEO",
    "department": "Directorio Corporativo",
    "phone": "+593 995095401",
    "email": "rosa.vargas70@yahoo.com",
    "address": "Calle 97 y Av. Principal, Quito",
    "dob": "1981-02-01",
    "photo": "https://i.pravatar.cc/150?img=33",
    "status": "Activo",
    "baseSalary": 637,
    "companyId": "femar"
  },
  {
    "id": "1721374336",
    "firstName": "Paola",
    "secondName": "Patricia",
    "firstLastName": "Romero",
    "secondLastName": "Delgado",
    "name": "Paola Patricia Romero Delgado",
    "role": "Supervisor de Ventas",
    "department": "Ventas",
    "phone": "+593 914305318",
    "email": "paola.romero1@hotmail.com",
    "address": "Calle 16 y Av. Principal, Quito",
    "dob": "1993-07-27",
    "photo": "https://i.pravatar.cc/150?img=10",
    "status": "Activo",
    "baseSalary": 2022,
    "companyId": "femar"
  },
  {
    "id": "0439491267",
    "firstName": "Carolina",
    "secondName": "Sofía",
    "firstLastName": "Vargas",
    "secondLastName": "Salazar",
    "name": "Carolina Sofía Vargas Salazar",
    "role": "Analista de Mercadeo",
    "department": "Marketing",
    "phone": "+593 982256369",
    "email": "carolina.vargas3@hotmail.com",
    "address": "Calle 15 y Av. Principal, Quito",
    "dob": "1976-09-02",
    "photo": "https://i.pravatar.cc/150?img=26",
    "status": "Activo",
    "baseSalary": 1628,
    "companyId": "femar"
  },
  {
    "id": "1040591180",
    "firstName": "Andrés",
    "secondName": "David",
    "firstLastName": "Sánchez",
    "secondLastName": "López",
    "name": "Andrés David Sánchez López",
    "role": "Especialista de RRHH",
    "department": "Recursos Humanos",
    "phone": "+593 965736292",
    "email": "andrés.sánchez68@yahoo.com",
    "address": "Calle 16 y Av. Principal, Quito",
    "dob": "1975-01-01",
    "photo": "https://i.pravatar.cc/150?img=21",
    "status": "Liquidado",
    "baseSalary": 1202,
    "companyId": "iapro"
  },
  {
    "id": "0256769753",
    "firstName": "Sofía",
    "secondName": "Elena",
    "firstLastName": "Navas",
    "secondLastName": "Zambrano",
    "name": "Sofía Elena Navas Zambrano",
    "role": "Desarrollador Backend",
    "department": "IT",
    "phone": "+593 937509749",
    "email": "sofía.navas24@hotmail.com",
    "address": "Calle 61 y Av. Principal, Quito",
    "dob": "1971-02-03",
    "photo": "https://i.pravatar.cc/150?img=57",
    "status": "Liquidado",
    "baseSalary": 903,
    "companyId": "iapro"
  },
  {
    "id": "1947279483",
    "firstName": "Daniela",
    "secondName": "Valeria",
    "firstLastName": "Delgado",
    "secondLastName": "Castro",
    "name": "Daniela Valeria Delgado Castro",
    "role": "Coordinador de Planta",
    "department": "Operaciones",
    "phone": "+593 964642555",
    "email": "daniela.delgado41@hotmail.com",
    "address": "Calle 60 y Av. Principal, Quito",
    "dob": "1981-02-23",
    "photo": "https://i.pravatar.cc/150?img=7",
    "status": "Vacaciones",
    "baseSalary": 726,
    "companyId": "iapro"
  },
  {
    "id": "2051182018",
    "firstName": "Fernando",
    "secondName": "David",
    "firstLastName": "Molina",
    "secondLastName": "Vargas",
    "name": "Fernando David Molina Vargas",
    "role": "Asesor Legal",
    "department": "Directorio Corporativo",
    "phone": "+593 940094080",
    "email": "fernando.molina96@gmail.com",
    "address": "Calle 49 y Av. Principal, Quito",
    "dob": "1997-01-03",
    "photo": "https://i.pravatar.cc/150?img=11",
    "status": "Activo",
    "baseSalary": 820,
    "companyId": "iapro"
  },
  {
    "id": "0927270843",
    "firstName": "Carolina",
    "secondName": "Isabel",
    "firstLastName": "Cevallos",
    "secondLastName": "Almeida",
    "name": "Carolina Isabel Cevallos Almeida",
    "role": "Key Account Manager",
    "department": "Ventas",
    "phone": "+593 986621032",
    "email": "carolina.cevallos98@outlook.com",
    "address": "Calle 57 y Av. Principal, Quito",
    "dob": "1986-06-04",
    "photo": "https://i.pravatar.cc/150?img=19",
    "status": "Activo",
    "baseSalary": 763,
    "companyId": "iapro"
  },
  {
    "id": "0527241137",
    "firstName": "Eduardo",
    "secondName": "Andrés",
    "firstLastName": "Cevallos",
    "secondLastName": "Guerrero",
    "name": "Eduardo Andrés Cevallos Guerrero",
    "role": "Analista de Mercadeo",
    "department": "Marketing",
    "phone": "+593 965064909",
    "email": "eduardo.cevallos16@outlook.com",
    "address": "Calle 77 y Av. Principal, Quito",
    "dob": "1995-01-19",
    "photo": "https://i.pravatar.cc/150?img=14",
    "status": "Activo",
    "baseSalary": 653,
    "companyId": "iapro"
  },
  {
    "id": "2108001716",
    "firstName": "Valeria",
    "secondName": "Elena",
    "firstLastName": "Rojas",
    "secondLastName": "Delgado",
    "name": "Valeria Elena Rojas Delgado",
    "role": "Analista de Nómina",
    "department": "Recursos Humanos",
    "phone": "+593 984118545",
    "email": "valeria.rojas76@outlook.com",
    "address": "Calle 41 y Av. Principal, Quito",
    "dob": "1989-12-17",
    "photo": "https://i.pravatar.cc/150?img=60",
    "status": "Vacaciones",
    "baseSalary": 715,
    "companyId": "iapro"
  },
  {
    "id": "0900865700",
    "firstName": "Jorge",
    "secondName": "Diego",
    "firstLastName": "Delgado",
    "secondLastName": "Salazar",
    "name": "Jorge Diego Delgado Salazar",
    "role": "SysAdmin",
    "department": "IT",
    "phone": "+593 998759686",
    "email": "jorge.delgado66@yahoo.com",
    "address": "Calle 61 y Av. Principal, Quito",
    "dob": "1981-04-06",
    "photo": "https://i.pravatar.cc/150?img=27",
    "status": "Activo",
    "baseSalary": 715,
    "companyId": "iapro"
  },
  {
    "id": "1221348350",
    "firstName": "Carmen",
    "secondName": "Valeria",
    "firstLastName": "Salazar",
    "secondLastName": "Guerrero",
    "name": "Carmen Valeria Salazar Guerrero",
    "role": "Coordinador de Planta",
    "department": "Operaciones",
    "phone": "+593 934941856",
    "email": "carmen.salazar70@gmail.com",
    "address": "Calle 60 y Av. Principal, Quito",
    "dob": "1974-07-23",
    "photo": "https://i.pravatar.cc/150?img=30",
    "status": "Permiso por Maternidad",
    "baseSalary": 2121,
    "companyId": "iapro"
  },
  {
    "id": "0118485762",
    "firstName": "Patricia",
    "secondName": "Sofía",
    "firstLastName": "Pérez",
    "secondLastName": "Ruiz",
    "name": "Patricia Sofía Pérez Ruiz",
    "role": "CEO",
    "department": "Directorio Corporativo",
    "phone": "+593 967389699",
    "email": "patricia.pérez69@gmail.com",
    "address": "Calle 9 y Av. Principal, Quito",
    "dob": "1992-04-12",
    "photo": "https://i.pravatar.cc/150?img=35",
    "status": "Activo",
    "baseSalary": 1741,
    "companyId": "iapro"
  },
  {
    "id": "1303059180",
    "firstName": "Andrea",
    "secondName": "Patricia",
    "firstLastName": "Navas",
    "secondLastName": "García",
    "name": "Andrea Patricia Navas García",
    "role": "Director de Ventas",
    "department": "Ventas",
    "phone": "+593 975988788",
    "email": "andrea.navas50@yahoo.com",
    "address": "Calle 55 y Av. Principal, Quito",
    "dob": "1987-05-11",
    "photo": "https://i.pravatar.cc/150?img=66",
    "status": "Activo",
    "baseSalary": 2059,
    "companyId": "pcdoctor"
  },
  {
    "id": "2401876210",
    "firstName": "Diana",
    "secondName": "Ana",
    "firstLastName": "Cruz",
    "secondLastName": "Delgado",
    "name": "Diana Ana Cruz Delgado",
    "role": "Analista de Mercadeo",
    "department": "Marketing",
    "phone": "+593 944596977",
    "email": "diana.cruz92@hotmail.com",
    "address": "Calle 57 y Av. Principal, Quito",
    "dob": "1996-07-17",
    "photo": "https://i.pravatar.cc/150?img=50",
    "status": "Activo",
    "baseSalary": 2050,
    "companyId": "pcdoctor"
  },
  {
    "id": "1816434805",
    "firstName": "Isabel",
    "secondName": "Laura",
    "firstLastName": "Pérez",
    "secondLastName": "García",
    "name": "Isabel Laura Pérez García",
    "role": "Especialista de RRHH",
    "department": "Recursos Humanos",
    "phone": "+593 971048260",
    "email": "isabel.pérez82@gmail.com",
    "address": "Calle 62 y Av. Principal, Quito",
    "dob": "1999-01-20",
    "photo": "https://i.pravatar.cc/150?img=11",
    "status": "Activo",
    "baseSalary": 2297,
    "companyId": "pcdoctor"
  },
  {
    "id": "1956957011",
    "firstName": "Laura",
    "secondName": "Isabel",
    "firstLastName": "Salazar",
    "secondLastName": "Sánchez",
    "name": "Laura Isabel Salazar Sánchez",
    "role": "Arquitecto Cloud",
    "department": "IT",
    "phone": "+593 992115666",
    "email": "laura.salazar35@hotmail.com",
    "address": "Calle 82 y Av. Principal, Quito",
    "dob": "1992-07-17",
    "photo": "https://i.pravatar.cc/150?img=16",
    "status": "Activo",
    "baseSalary": 1210,
    "companyId": "pcdoctor"
  },
  {
    "id": "1649359922",
    "firstName": "Diego",
    "secondName": "Andrés",
    "firstLastName": "Sánchez",
    "secondLastName": "Paz",
    "name": "Diego Andrés Sánchez Paz",
    "role": "Supervisor Logístico",
    "department": "Operaciones",
    "phone": "+593 947702686",
    "email": "diego.sánchez67@hotmail.com",
    "address": "Calle 79 y Av. Principal, Quito",
    "dob": "1975-05-11",
    "photo": "https://i.pravatar.cc/150?img=48",
    "status": "Vacaciones",
    "baseSalary": 2396,
    "companyId": "pcdoctor"
  }
];
