import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, Bot, CalendarDays, CheckCircle2, Clock3, Fingerprint, Gauge, MapPin, Menu, Mic2, ScanFace, Users, WalletCards } from 'lucide-react';
import './styles.css';

type Page = 'dashboard' | 'events' | 'mobile' | 'payroll' | 'integrations';

const employees = [
  { name: 'Ana Córdova', area: 'Administración', base: 725, overtime: 42.25, night: 0, deductions: 8.4 },
  { name: 'Carlos Mendoza', area: 'Operaciones', base: 610, overtime: 61.1, night: 18.3, deductions: 0 },
  { name: 'María Valencia', area: 'Comercial', base: 690, overtime: 0, night: 0, deductions: 12.2 },
  { name: 'David Herrera', area: 'Logística', base: 580, overtime: 33.6, night: 24.15, deductions: 5.75 },
  { name: 'Paula Santos', area: 'Talento Humano', base: 760, overtime: 0, night: 0, deductions: 0 }
].map((employee) => ({ ...employee, net: employee.base + employee.overtime + employee.night - employee.deductions }));

const money = (value: number) => new Intl.NumberFormat('es-EC', { style: 'currency', currency: 'USD' }).format(value);
const totals = employees.reduce((acc, row) => ({ base: acc.base + row.base, additions: acc.additions + row.overtime + row.night, deductions: acc.deductions + row.deductions, net: acc.net + row.net }), { base: 0, additions: 0, deductions: 0, net: 0 });

const cards = [
  ['Empleados activos', '122', '100 marcaron hoy', Users],
  ['Marcaciones', '248', 'SenseFace + móvil', Fingerprint],
  ['Excepciones', '9', '4 requieren revisión', AlertTriangle],
  ['Pre-nómina demo', money(totals.net), 'Período quincenal', WalletCards]
] as const;

function Nav({ page, setPage }: { page: Page; setPage: (page: Page) => void }) {
  const items: [Page, string, React.ElementType][] = [['dashboard', 'Resumen', Gauge], ['events', 'Asistencia', Clock3], ['mobile', 'Marcación móvil', MapPin], ['payroll', 'Pre-nómina', WalletCards], ['integrations', 'Integraciones', Bot]];
  return <aside><div className="brand"><span className="spark">✦</span><div><strong>InnerSpark</strong><small>Workforce AI</small></div></div><nav>{items.map(([id, label, Icon]) => <button className={page === id ? 'active' : ''} onClick={() => setPage(id)} key={id}><Icon size={18}/>{label}</button>)}</nav><div className="demo"><span>DEMO</span><b>FEMAR</b><small>Datos ficticios</small></div></aside>;
}

function Header({ title }: { title: string }) { return <header><button className="menu"><Menu size={20}/></button><div><h1>{title}</h1><p>FEMAR · UTC-5 · Datos demostrativos</p></div><div className="live"><i/>Sistema operativo</div></header>; }

function Dashboard() { return <><Header title="Centro de control"/><section className="hero"><div><span className="eyebrow">ASISTENCIA + PRE-NÓMINA</span><h2>Del marcaje al valor,<br/>sin reprocesos.</h2><p>Una sola trazabilidad para equipos ZKTeco, personal en campo y reglas monetarias explicables.</p></div><div className="ai"><Bot/><b>Revisión IA</b><strong>4 alertas críticas</strong><small>No cerrar el período hasta resolver 2 ausencias y 2 marcaciones incompletas.</small></div></section><section className="cards">{cards.map(([label, value, note, Icon]) => <article key={label}><div className="icon"><Icon size={20}/></div><small>{label}</small><strong>{value}</strong><p>{note}</p></article>)}</section><section className="grid"><article className="panel"><div className="panel-title"><div><h3>Actividad reciente</h3><p>Eventos normalizados desde todas las fuentes</p></div><span className="badge">EN VIVO</span></div>{['Ana Córdova|Entrada|08:01|SenseFace 2A','Carlos Mendoza|Entrada|07:54|ZKTeco K20','María Valencia|Entrada|08:03|PWA · GPS','David Herrera|Salida|12:15|SenseFace 2A'].map((x) => { const [n,e,t,s]=x.split('|'); return <div className="event" key={x}><span className="avatar">{n[0]}</span><div><b>{n}</b><small>{e} · {s}</small></div><time>{t}</time><CheckCircle2 size={17}/></div>})}</article><article className="panel"><div className="panel-title"><div><h3>Estado de dispositivos</h3><p>Última comunicación</p></div></div><Device name="SenseFace 2A" place="Acceso principal" online/><Device name="ZKTeco K20" place="Bodega" online/><Device name="Bridge TCP 4370" place="Agente local" online/><Device name="ADMS Cloud" place="Google Cloud Run" online/><Device name="WL-700" place="Planta"/></article></section></>; }
function Device({ name, place, online=false }: {name:string;place:string;online?:boolean}) { return <div className="device"><ScanFace/><div><b>{name}</b><small>{place}</small></div><span className={online?'ok':'off'}>{online?'En línea':'Revisar'}</span></div> }

function Events() { return <><Header title="Asistencia y novedades"/><section className="section-head"><div><span className="eyebrow">TRAZABILIDAD</span><h2>Marcaciones unificadas</h2></div><button className="primary">Procesar novedades</button></section><article className="panel table"><div className="filters"><input placeholder="Buscar empleado…"/><button>Hoy</button><button>Todos los equipos</button></div><table><thead><tr><th>Empleado</th><th>Evento</th><th>Fecha y hora</th><th>Fuente</th><th>Estado</th></tr></thead><tbody>{['Ana Córdova|Entrada|14 mar 2025 · 08:01|SenseFace 2A|Válido','Carlos Mendoza|Entrada|14 mar 2025 · 07:54|ZKTeco K20|Válido','María Valencia|Entrada|14 mar 2025 · 08:03|PWA GPS + foto|Válido','Diego Ramírez|Salida|13 mar 2025 · —|Sin marcación|Crítico'].map(r=><tr key={r}>{r.split('|').map((c,i)=><td key={i}><span className={c==='Crítico'?'danger':''}>{c}</span></td>)}</tr>)}</tbody></table></article></>; }

function MobilePunch() { const [captured,setCaptured]=useState(false); const capture=()=>navigator.geolocation?.getCurrentPosition(()=>setCaptured(true),()=>setCaptured(true)); return <><Header title="Marcación móvil"/><section className="mobile-wrap"><article className="phone"><div className="phone-top">InnerSpark <span>08:02</span></div><div className="face"><ScanFace size={64}/><i className={captured?'captured':''}/></div><h2>{captured?'Marcación registrada':'Hola, María'}</h2><p>{captured?'Ubicación y evidencia guardadas':'Ubícate dentro de la zona autorizada'}</p><div className="location"><MapPin/><div><b>FEMAR · Matriz</b><small>Precisión estimada: 12 m</small></div></div><button className="capture" onClick={capture}>{captured?<CheckCircle2/>:<Fingerprint/>}{captured?'Entrada confirmada':'Registrar entrada'}</button><small className="privacy">La foto no se publica. Se conserva según la política de FEMAR.</small></article><article className="mobile-copy"><span className="eyebrow">PWA DE CAMPO</span><h2>GPS, geocerca, foto y modo sin conexión.</h2><p>La app guarda un identificador único cuando no hay señal y sincroniza sin duplicar la marcación.</p><ul><li><MapPin/> Validación de radio permitido</li><li><ScanFace/> Evidencia fotográfica autorizada</li><li><Clock3/> Cola offline con sello de tiempo</li></ul></article></section></>; }

function Payroll() { return <><Header title="Pre-nómina explicable"/><section className="section-head"><div><span className="eyebrow">PERÍODO 1–15 MARZO 2025</span><h2>Cálculo reconciliado</h2><p>Base quincenal = salario mensual ÷ 2. Datos ficticios.</p></div><button className="primary">Exportar CSV</button></section><section className="paycards"><article><small>Base</small><b>{money(totals.base)}</b></article><article><small>Extras y recargos</small><b>{money(totals.additions)}</b></article><article><small>Descuentos</small><b>-{money(totals.deductions)}</b></article><article className="net"><small>Neto estimado</small><b>{money(totals.net)}</b></article></section><article className="panel table"><table><thead><tr><th>Empleado</th><th>Área</th><th>Base</th><th>Extras</th><th>Nocturno</th><th>Descuentos</th><th>Neto</th></tr></thead><tbody>{employees.map(e=><tr key={e.name}><td><b>{e.name}</b></td><td>{e.area}</td><td>{money(e.base)}</td><td>{money(e.overtime)}</td><td>{money(e.night)}</td><td>{money(e.deductions)}</td><td><b>{money(e.net)}</b></td></tr>)}</tbody><tfoot><tr><td colSpan={6}>Suma de empleados = neto del período</td><td>{money(totals.net)}</td></tr></tfoot></table></article><div className="warning"><AlertTriangle/><div><b>Pre-nómina, no rol legal definitivo</b><p>Las reglas deben ser aprobadas por Talento Humano y el asesor laboral antes de producción.</p></div></div></>; }

function Integrations() { return <><Header title="Integraciones"/><section className="section-head"><div><span className="eyebrow">ECOSISTEMA</span><h2>Servicios y patrocinadores</h2></div></section><section className="integration-grid"><Integration icon={ScanFace} name="SenseFace 2A" text="ADMS / HTTP Push" state="Preparado"/><Integration icon={Fingerprint} name="ZKTeco heredado" text="Bridge local TCP 4370" state="Preparado"/><Integration icon={Bot} name="AI/ML API" text="Análisis de novedades" state="Por conectar"/><Integration icon={Mic2} name="Speechmatics" text="Justificaciones por voz" state="Por conectar"/><Integration icon={CalendarDays} name="Bright Data" text="Fuentes públicas verificables" state="Por conectar"/><Integration icon={Gauge} name="Google Cloud" text="Cloud Run + PostgreSQL" state="Configurable"/></section></>; }
function Integration({icon:Icon,name,text,state}:{icon:React.ElementType;name:string;text:string;state:string}) { return <article className="integration"><Icon/><div><b>{name}</b><p>{text}</p></div><span>{state}</span></article> }

function App() { const [page,setPage]=useState<Page>('dashboard'); const content={dashboard:<Dashboard/>,events:<Events/>,mobile:<MobilePunch/>,payroll:<Payroll/>,integrations:<Integrations/>}[page]; return <div className="app"><Nav page={page} setPage={setPage}/><main>{content}</main></div> }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
